config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  #管理端
  namespace :admin do
    root 'banners#index'
    resources :banners
    resources :pages
    resources :products
    resources :orders
  end
end

app/models/banner.rb
class Banner < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < Admin::BaseController
	def index
		@banners = Banner.all
	end

	def new
		@banner = Banner.new
	end

	def create
		@banner = Banner.new(banner_params)
		if @banner.save
			redirect_to admin_banners_path
		else
			render :new
		end
	end

	def edit
		@banner = Banner.find(params[:id])
	end

	def update
		@banner = Banner.find(params[:id])
		if @banner.update(banner_params)
			redirect_to admin_banners_path
		else
			render :edit
		end
	end

	private
	def banner_params
		params.require(:banner).permit(:name, :image)
	end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController
	def index
		@pages = Page.all
	end

	def new
		@page = Page.new
	end

	def create
		@page = Page.new(page_params)
		if @page.save
			redirect_to admin_pages_path
		else
			render :new
		end
	end

	def edit
		@page = Page.find(params[:id])
	end

	def update
		@page = Page.find(params[:id])
		if @page.update(page_params)
			redirect_to admin_pages_path
		else
			render :edit
		end
	end

	private

	def page_params
		params.require(:page).permit(:content)
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to admin_products_path
		else
			render :new
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to admin_products_path
		else
			render :edit
		end
	end

	private
	def product_params
		params.require(:product).permit(:productname, :price)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/banners/edit.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
  <div id="wrapper" class="full">
    <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
      <div id="content" class="max">
        <div class="tables">
          <h4>廣告橫幅</h4>                
          <div class="row">
            <div class="col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading">Banners</div>
                <div class="panel-body">
                  <%= bootstrap_form_for @banner, url: admin_banner_path(@banner) do |n| %>
                    <div class="form-group">
                      <label class="col-sm-2 control-label">上傳橫幅</label>
                      <div class="col-sm-10">
                          <%= n.text_field :name %>
                          <%= n.file_field :image %>
                          <%= n.submit '更新', class: :"btn btn-green" %>
                          <%= link_to('返回', admin_banners_path, class: :"btn btn-green") %>
                      </div>                                        
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>                
        </div>
      </div>
    <div class="clearfix"></div>
  </div>
  <!-- Content End -->
</body>

app/views/admin/banners/index.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
  <div id="wrapper" class="full">
      <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
      <div id="content" class="max">
          <div class="tables">
              <h4>廣告橫幅</h4>
              <div class="panel panel-default">
                  <div class="panel-heading">清單</div>
                  <div class="row tableContainer">
                      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                          <%= link_to new_admin_banner_path, class: :"btn btn-sm btn-yellow mb5" do %>
                            <span class="fa fa-edit"></span>新增</a>
                          <% end %>

                      </div>
                  </div>
                  <div class="table-overflow">
                      <table class="table" id="inboxTable">
                          <thead>
                              <tr>                                  
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 橫幅名稱</th>
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 圖片</th>
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 動作</th>
                              </tr>
                          </thead>
                          <tbody class="table">
                          <% @banners.each do |i| %>
                              <tr>
                                  <td><%= i.name %></td>
                                  <td><%= image_tag i.image_url(:small) %></td>
                                  <td><%= link_to new_admin_banner_path, class: :"btn btn-sm btn-blue mb5" do %>
                                      <span class="fa fa-edit"></span>編輯</a>
                                      <% end %>
                                  </td>
                              </tr>
                          <% end %>
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
      <div class="clearfix"></div>
  </div>
  <!-- Content End-->
</body>

app/views/admin/banners/new.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
  <div id="wrapper" class="full">
    <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
      <div id="content" class="max">
        <div class="tables">
          <h4>廣告橫幅</h4>                
          <div class="row">
            <div class="col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading">Banners</div>
                <div class="panel-body">
                  <%= bootstrap_form_for @banner, url: admin_banners_path(@banner) do |n| %>
                    <div class="form-group">
                      <label class="col-sm-2 control-label">上傳橫幅</label>
                      <div class="col-sm-10">
                          <%= n.text_field :name %>
                          <%= n.file_field :image %>
                          <%= n.submit '送出', class: :"btn btn-green" %>
                          <%= link_to('返回', admin_banners_path, class: :"btn btn-green") %>
                      </div>                                        
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>                
        </div>
      </div>
    <div class="clearfix"></div>
  </div>
  <!-- Content End -->
</body>

app/views/admin/products/edit.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
  <div id="wrapper" class="full">
    <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
      <div id="content" class="max">
        <div class="tables">
          <h4>編輯商品</h4>                
          <div class="row">
            <div class="col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading">Products</div>
                <div class="panel-body">
                  <%= bootstrap_form_for @product, url: admin_product_path(@product) do |n| %>
                    <div class="form-group">
                      <label class="col-sm-2 control-label">編輯</label>
                      <div class="col-sm-10">
                          <%= n.text_field :productname %>
                          <%= n.text_field :price %>
                          <%= n.submit '保存', class: :"btn btn-green" %>
                          <%= link_to('返回', admin_banners_path, class: :"btn btn-green") %>
                      </div>                                        
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>                
        </div>
      </div>
    <div class="clearfix"></div>
  </div>
  <!-- Content End -->
</body>

app/views/admin/products/index.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
  <div id="wrapper" class="full">
      <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
      <div id="content" class="max">
          <div class="tables">
              <h4>商品管理</h4>
              <div class="panel panel-default">
                  <div class="panel-heading">清單</div>
                  <div class="row tableContainer">
                      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                          <%= link_to new_admin_product_path, class: :"btn btn-sm btn-yellow mb5" do %>
                            <span class="fa fa-edit"></span>新增</a>
                          <% end %>

                      </div>
                  </div>
                  <div class="table-overflow">
                      <table class="table" id="inboxTable">
                          <thead>
                              <tr>                                  
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 商品名稱</th>
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 商品價格</th>
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 動作</th>
                              </tr>
                          </thead>
                          <tbody class="table">
                          <% @products.each do |i| %>
                              <tr>
                                  <td><%= i.productname %></td>
                                  <td><%= i.price %></td>
                                  <td><%= link_to edit_admin_product_path(i), class: :"btn btn-sm btn-blue mb5" do %>
                                      <span class="fa fa-edit"></span>編輯</a>
                                      <% end %>
                                  </td>
                              </tr>
                          <% end %>
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
      <div class="clearfix"></div>
  </div>
  <!-- Content End-->
</body>

app/views/admin/products/new.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
  <div id="wrapper" class="full">
    <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
      <div id="content" class="max">
        <div class="tables">
          <h4>新增商品</h4>                
          <div class="row">
            <div class="col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading">Products</div>
                <div class="panel-body">
                  <%= bootstrap_form_for @product, url: admin_products_path(@product) do |n| %>
                    <div class="form-group">
                      <label class="col-sm-2 control-label">新增</label>
                      <div class="col-sm-10">
                          <%= n.text_field :productname %>
                          <%= n.text_field :price %>
                          <%= n.submit '送出', class: :"btn btn-green" %>
                          <%= link_to('返回', admin_banners_path, class: :"btn btn-green") %>
                      </div>                                        
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>                
        </div>
      </div>
    <div class="clearfix"></div>
  </div>
  <!-- Content End -->
</body>