config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  #管理端
  namespace :admin do
    root 'banners#index'
    resources :banners
    resources :pages
    resources :products
    resources :orders
  end
end

app/models/banner.rb
class Banner < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController
	def index
		@pages = Page.all
	end

	def new
		@page = Page.new
	end

	def create
		@page = Page.new(page_params)
		if @page.save
			redirect_to admin_pages_path
		else
			render :new
		end
	end

	def edit
		@page = Page.find(params[:id])
	end

	def update
		@page = Page.find(params[:id])
		if @page.update(page_params)
			redirect_to admin_pages_path
		else
			render :edit
		end
	end

	private

	def page_params
		params.require(:page).permit(:content)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/common/_header.html.erb
<div id="header">
    <div class="logo">
        <a href="index.html">
            <span class="fa fa-home marker"></span>
            <span class="logoText">Shampoo</span>
        </a>
    </div>
    <a href="#" class="navHandler"><span class="fa fa-bars"></span></a>
    <div class="search">
        <span class="searchIcon icon-magnifier"></span>
        <input type="text" placeholder="Search for houses, apartments...">
    </div>
    <div class="headerUserWraper">
        <a href="#" class="userHandler dropdown-toggle" data-toggle="dropdown"><span class="icon-user"></span><span class="counter">5</span></a>
        <a href="#" class="headerUser dropdown-toggle" data-toggle="dropdown">
            <img class="avatar headerAvatar pull-left" src="/assets/images/avatar-1.png" alt="avatar">
            <div class="userTop pull-left">
                <span class="headerUserName">John Smith</span> <span class="fa fa-angle-down"></span>
            </div>
            <div class="clearfix"></div>
        </a>
        <div class="dropdown-menu pull-right userMenu" role="menu">
            <div class="mobAvatar">
                <img class="avatar mobAvatarImg" src="/assets/images/avatar-1.png" alt="avatar">
                <div class="mobAvatarName">John Smith</div>
            </div>
            <ul>
                <li><a href="#"><span class="icon-settings"></span>Settings</a></li>
                <li><a href="profile.html"><span class="icon-user"></span>Profile</a></li>
                <li><a href="#"><span class="icon-bell"></span>Notifications <span class="badge pull-right bg-red">5</span></a></li>
                <li class="divider"></li>
                <li><a href="#"><span class="icon-power"></span>Logout</a></li>
            </ul>
        </div>
    </div>
    <div class="headerNotifyWraper">
        <a href="#" class="headerNotify dropdown-toggle" data-toggle="dropdown">
            <span class="notifyIcon icon-bell"></span>
            <span class="counter">5</span>
        </a>
        <div class="dropdown-menu pull-right notifyMenu" role="menu">
            <div class="notifyHeader">
                <span>Notifications</span>
                <a href="#" class="notifySettings icon-settings"></a>
                <div class="clearfix"></div>
            </div>
            <ul class="notifyList">
                <li>
                    <a href="#">
                        <img class="avatar pull-left" src="/assets/images/avatar-1.png" alt="avatar">
                        <div class="pulse border-grey"></div>
                        <div class="notify pull-left">
                            <div class="notifyName">Sed ut perspiciatis unde</div>
                            <div class="notifyTime">5 minutes ago</div>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="notifyRound notifyRound-red fa fa-envelope-o"></div>
                        <div class="pulse border-red"></div>
                        <div class="notify pull-left">
                            <div class="notifyName">Lorem Ipsum is simply dummy text</div>
                            <div class="notifyTime">20 minutes ago</div>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="notifyRound notifyRound-yellow fa fa-heart-o"></div>
                        <div class="pulse border-yellow"></div>
                        <div class="notify pull-left">
                            <div class="notifyName">It is a long established fact</div>
                            <div class="notifyTime">2 hours ago</div>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="notifyRound notifyRound-magenta fa fa-paper-plane-o"></div>
                        <div class="pulse border-magenta"></div>
                        <div class="notify pull-left">
                            <div class="notifyName">There are many variations</div>
                            <div class="notifyTime">1 day ago</div>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
            </ul>
            <a href="#" class="notifyAll">See All</a>
        </div>
    </div>
    <a href="#" class="mapHandler"><span class="icon-map"></span></a>
    <div class="clearfix"></div>
</div>

app/views/admin/common/_menu.html.erb
<div id="leftSide">
    <nav class="leftNav scrollable">
        <div class="search">
            <span class="searchIcon icon-magnifier"></span>
            <input type="text" placeholder="Search for houses, apartments...">
            <div class="clearfix"></div>
        </div>
        <ul>
            <li>
              <%= link_to admin_banners_path do %>
                <span class="navIcon icon-compass"></span><span class="navLabel">橫幅管理</span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_pages_path do %>
                <span class="navIcon icon-compass"></span><span class="navLabel">文案管理</span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_products_path do %>
                <span class="navIcon icon-plus"></span><span class="navLabel">商品管理</span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_orders_path do %>
                <span class="navIcon icon-plus"></span><span class="navLabel">訂單管理</span>
              <% end %>
            </li>
            <li class="hasSub">
                <a href="#"><span class="navIcon icon-layers"></span><span class="navLabel">Elements</span><span class="fa fa-angle-left arrowRight"></span></a>
                <ul>
                    <li><a href="buttons.html">Buttons</a></li>
                    <li><a href="icons.html">Icons <span class="badge pull-right bg-yellow">841</span></a></li>
                    <li><a href="grid.html">Grid</a></li>
                    <li><a href="widgets.html">Widgets</a></li>
                    <li><a href="components.html">Components</a></li>
                    <li><a href="lists.html">Lists</a></li>
                    <li><a href="tables.html">Tables</a></li>
                    <li><a href="form.html">Form</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</div>
<div class="closeLeftSide"></div>

app/views/admin/pages/edit.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
	<div id="wrapper" class="full">
	  <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
	  <div id="content" class="max">
	    <div class="tables">
	      <h4>編輯文案</h4>      
	      <div class="row">
	        <div class="col-xs-12">
	          <div class="panel panel-default">	            
	            <div class="panel-body">
	              <%= bootstrap_form_for @page, url: admin_page_path(@page) do |n| %>
	              	<div class="form-group">
	              		<%= n.submit '送出', class: :"btn btn-round btn-green" %>
	              		<%= link_to('返回', admin_pages_path, class: :"btn btn-round btn-green") %>
	              	</div>
	                <div class="form-group">	                	
  									<%= n.cktext_area :content, :ckeditor => {:language => 'uk'}, :cols => 40, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'}  %>
	                </div>  
	              <% end %>                                    
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>
	  <div class="clearfix"></div>
	</div>
  <!-- Content End-->
</body>

app/views/admin/pages/index.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
	<div id="wrapper" class="full">
      <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
      <div id="content" class="max">
          <div class="tables">
              <h4>文案</h4>
              <div class="panel panel-default">
                  <div class="panel-heading">清單</div>
                  <div class="row tableContainer">
                      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                          <%= link_to new_admin_page_path, class: :"btn btn-sm btn-yellow mb5" do %>
                            <span class="fa fa-edit"></span>新增</a>
                          <% end %>

                      </div>
                  </div>
                  <div class="table-overflow">
                      <table class="table" id="inboxTable">
                          <thead>
                              <tr>                                  
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 文案內容</th>
                                  <th><span class="fa fa-sort sortIcon"></span><span class="fa fa-caret-up sortIconAsc"></span><span class="fa fa-caret-down sortIconDesc"></span> 動作</th>
                              </tr>
                          </thead>
                          <tbody class="table">
                          <% @pages.each do |i| %>
                              <tr>
                                  <td><%= i.name %></td>
                                  <td><%= link_to edit_admin_page_path, class: :"btn btn-sm btn-blue mb5" do %>
                                      <span class="fa fa-edit"></span>編輯</a>
                                      <% end %>
                                  </td>
                              </tr>
                          <% end %>
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
      <div class="clearfix"></div>
  </div>
  <!-- Content End-->
</body>

app/views/admin/pages/new.html.erb
<body class="notransition">
  <!-- Header -->
  <%= render 'admin/common/header' %>
  <!-- Header End -->
  <!-- Left Side Navigation -->    
  <%= render 'admin/common/menu' %>
  <!-- Left Side Navigation End -->
  <!-- Content -->
	<div id="wrapper" class="full">
	  <div id="mapView" class="min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Loading map...</div></div>
	  <div id="content" class="max">
	    <div class="tables">
	      <h4>新增文案</h4>      
	      <div class="row">
	        <div class="col-xs-12">
	          <div class="panel panel-default">	            
	            <div class="panel-body">
	              <%= bootstrap_form_for @page, url: admin_pages_path(@page) do |n| %>
	              	<div class="form-group">
	              		<%= n.submit '送出', class: :"btn btn-round btn-green" %>
	              		<%= link_to('返回', admin_pages_path, class: :"btn btn-round btn-green") %>
	              	</div>
	                <div class="form-group">	                	
  									<%= n.cktext_area :content, :ckeditor => {:language => 'uk'}, :cols => 40, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'}  %>
	                </div>  
	              <% end %>                                    
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>
	  <div class="clearfix"></div>
	</div>
  <!-- Content End-->
</body>

app/views/common/head.html.erb
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>reales | real estate web application</title>

    <link href="css/font-awesome.css" rel="stylesheet">
    <link href="css/simple-line-icons.css" rel="stylesheet">
    <link href="css/jquery-ui.css" rel="stylesheet">
    <link href="css/jquery.tagsinput.css" rel="stylesheet">
    <link href="css/datepicker.css" rel="stylesheet">
    <link href="css/fileinput.min.css" rel="stylesheet">
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/app.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shampoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
</head>
<body>

<%= yield %>



	<script src="http://maps.googleapis.com/maps/api/js?sensor=true&amp;libraries=geometry&amp;libraries=places" type="text/javascript"></script>
	<script src="/assets/jquery-2.1.1.min.js"></script>
	<script src="/assets/jquery-ui.min.js"></script>
	<script src="/assets/jquery-ui-touch-punch.js"></script>
	<script src="/assets/jquery.placeholder.js"></script>
	<script src="/assets/bootstrap.js"></script>
	<script src="/assets/jquery.touchSwipe.min.js"></script>
	<script src="/assets/jquery.slimscroll.min.js"></script>
	<script src="/assets/infobox.js"></script>
	<script src="/assets/jquery.tagsinput.min.js"></script>
	<script src="/assets/bootstrap-datepicker.js"></script>
	<script src="/assets/app.js" type="text/javascript"></script>

</body>
</html>